### ISSUE TITLE
issue in running, هل عندك علم في هذي المشكله ام لا 

### ISSUE THREAD

**Issue by ahmad-algsham** [adhaamehab/textblob-ar#18]
Traceback (most recent call last):
  File "C:/Users/ahmad/PycharmProjects/gittingdata/سثؤخىي صشغ/textblobarabic.py", line 5, in <module>
    blobb = TextBlob("""هندسة البرمجيات هي دراسة تصميم وتنفيذ وتعديل البرمجيات بما يضمن توفر هذه البرمجيات بجودة عالية وتكلفة معقولة متاحة للجميع وقابلة للتطوير فيما بعد وسريعة للبناء. وهندسة البرمجيات تقوم على أسس ونظريات من الهندسة وعلوم الحاسب كمبدأ ال Functional Structure من الهندسة والذي يعتمد على مبدأ تصميم أجزاء صغيرة تتجانس في العمل مع بعضها لتشكل عمل الك""")
  File "C:\Users\ahmad\PycharmProjects\gittingdata\venv\lib\site-packages\textblob_ar\blob.py", line 71, in __init__
    _pos_tagger = pos_tagger if pos_tagger is not None else StanfordPartOfSpeechTagger()
  File "C:\Users\ahmad\PycharmProjects\gittingdata\venv\lib\site-packages\textblob_ar\pos_tagger.py", line 12, in __init__
    self._tagger = StanfordPOSTagger(modelPath, modelJar)
  File "C:\Users\ahmad\PycharmProjects\gittingdata\venv\lib\site-packages\nltk\tag\stanford.py", line 160, in __init__
    super(StanfordPOSTagger, self).__init__(*args, **kwargs)
  File "C:\Users\ahmad\PycharmProjects\gittingdata\venv\lib\site-packages\nltk\tag\stanford.py", line 74, in __init__
    self._JAR, path_to_jar, searchpath=(), url=_stanford_url, verbose=verbose
  File "C:\Users\ahmad\PycharmProjects\gittingdata\venv\lib\site-packages\nltk\internals.py", line 854, in find_jar
    name_pattern, path_to_jar, env_vars, searchpath, url, verbose, is_regex
  File "C:\Users\ahmad\PycharmProjects\gittingdata\venv\lib\site-packages\nltk\internals.py", line 740, in find_jar_iter
    'Could not find %s jar file at %s' % (name_pattern, path_to_jar)
LookupError: Could not find stanford-postagger.jar jar file at textblob_ar/data/model.jar

**Comment by Muath-Alsaeed** [comment]
i have the solution's

**Comment by RanaFakeeh-87** [comment]
هل وجدت حلا ام لا؟

**Comment by mahdiMokadem** [comment]
any solution was found?

**Comment by Muath-Alsaeed** [comment]
yes

‫في الأحد، 11 أكتوبر 2020 في 7:47 م تمت كتابة ما يلي بواسطة ‪mahdiMokadem‬‏
<‪notifications@github.com‬‏>:‬

**Comment by mahdiMokadem** [comment]
ok, so what was the solution?

**Comment by bmd94** [comment]
hi guys, i have the same problem :'(

**Comment by eman85** [comment]
i have the same problem , can any one please share the solution   ?
